cargo-features = ["profile-rustflags"]
[workspace]
members = [
    "acpi",
    "base_driver",
    "disk",
    "fat32",
    "i8042",
    "ide",
    "mountmgr",
    "partmgr",
    "pci",
    "virtio",
    "volmgr",
]
resolver = "2"

[profile.dev]
opt-level = 3
panic = "abort"
lto = true
codegen-units = 1
debug = true

[profile.release]
panic = "abort"
opt-level = 3
lto = true
codegen-units = 1
debug = true
