cargo-features = ["profile-rustflags"]
[workspace]
members = [
    "acpi",
    "base_driver",
    "disk",
    "fat32",
    "i8042",
    "ide",
    "mountmgr",
    "partmgr",
    "pci",
    "virtio",
    "volmgr",
]
resolver = "2"

[profile.dev]
panic = "abort"
lto = true
codegen-units = 1

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
