[package]
name = "acpi"
version.workspace = true
edition.workspace = true
autotests = false

[lib]
name = "acpi"
path = "src/lib.rs"
crate-type = ["cdylib"]
test = false

[dependencies]
kernel_api.workspace = true
spin.workspace = true
aml.workspace = true
