[package]
name = "disk"
version.workspace = true
edition.workspace = true
autotests = false

[lib]
name = "disk"
path = "src/lib.rs"
crate-type = ["cdylib"]
test = false

[dependencies]
kernel_api.workspace = true
spin.workspace = true
bitflags.workspace = true
